# Generated by Django 3.2.9 on 2021-11-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20211102_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watch_links',
            new_name='Movielink',
        ),
    ]
