# Generated by Django 3.2.9 on 2021-11-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_watch_links_movielink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('comedy', 'COMEDY'), ('drama', 'DRAMA'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('kid', 'KID'), ('roomance', 'ROMANCE'), ('science-fiction', 'SCIENCE-FICTION')], max_length=15),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='type',
            field=models.CharField(choices=[('Download', 'DOWNLOAD LINK'), ('Watch', 'WATCH LINK')], max_length=8),
        ),
    ]
