# Generated by Django 3.2.9 on 2021-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('anglais', 'ENGLISH'), ('français', 'FRENCH')], max_length=8),
        ),
    ]
