# Generated by Django 3.2.9 on 2021-11-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
