# Generated by Django 3.2.9 on 2021-11-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_movie_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
    ]
